### ISSUE TITLE
I've learned about fddtype.

### ISSUE THREAD

**Issue by KOZ39** [barbeque/pc98-disk-tools#5]
https://github.com/barbeque/pc98-disk-tools/blob/067faf57d30bcb153648464e1891ac05185d0dbf/hdm_to_fdi.py#L49

I think this means 1.44MB floppy disk.

**Comment by KOZ39** [comment]
Oops, sorry.
144 is 1.2MB - 2HD.

```hex(144 & 0xf0) = 0x90```

| Case         | Disk Size | Disk Type |
|--------------|-----------|-----------|
| 0x10         | 1MB/640KB | 2DD       |
| 0x30<br>0xb0 | 1.44MB    | 2HD       |
| 0x50<br>0xd0 | 320KB     | 2D        |
| 0x70<br>0xf0 | 640KB     | 2DD       |
| 0x90          | 1.2MB     | 2HD       |

https://github.com/nonakap/xnp2/blob/9a0baa69548cfa00c9f57ba26be8fc54e8f55272/fdd/fdd_xdf.c#L129-L151

**Comment by barbeque** [comment]
Thank you for the information! I have updated the comment in that file.

**Comment by KOZ39** [comment]
Yes, and next time, writing a commit message like Fix to comment # 5 will make things easier. :wink:

**Comment by KOZ39** [comment]
Yes, and next time, writing a commit message like 'Fix to comment #5' will make things easier. :wink:
